# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=128)),
                ('zip', models.IntegerField()),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
    ]
